"use node";

import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
  HeadObjectCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { v4 as uuidv4 } from "uuid";
import { promises as fs, existsSync } from "node:fs";
import path from "node:path";
import {
  getS3UrlLifetimeSeconds,
  S3_USER_FILES_PREFIX,
} from "../lib/constants/s3";

/**
 * Get environment variable with validation
 */
function getRequiredEnvVar(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

/**
 * Get S3 client with credentials from environment variables
 */
export function getS3Client(): S3Client {
  const accessKeyId = getRequiredEnvVar("AWS_S3_ACCESS_KEY_ID");
  const secretAccessKey = getRequiredEnvVar("AWS_S3_SECRET_ACCESS_KEY");
  const region = getRequiredEnvVar("AWS_S3_REGION");

  return new S3Client({
    region,
    credentials: {
      accessKeyId,
      secretAccessKey,
    },
  });
}

/**
 * Whether S3 is fully configured. When AWS env vars are missing (e.g. local
 * personal mode), file storage falls back to the local filesystem.
 */
export function isS3Configured(): boolean {
  return Boolean(
    process.env.AWS_S3_ACCESS_KEY_ID &&
      process.env.AWS_S3_SECRET_ACCESS_KEY &&
      process.env.AWS_S3_REGION &&
      process.env.AWS_S3_BUCKET_NAME,
  );
}

/**
 * Base URL used by local-storage upload/download endpoints. Overridable via
 * LOCAL_STORAGE_BASE_URL.
 */
function getLocalStorageBaseUrl(): string {
  return process.env.LOCAL_STORAGE_BASE_URL || "http://127.0.0.1:3000";
}

/**
 * Local storage root directory. Uses LOCAL_STORAGE_DIR when set, otherwise
 * resolves ".local-storage" relative to the repository root (walking up from
 * the current working directory, since Convex's Node runtime may chdir).
 */
function getLocalStorageDir(): string {
  if (process.env.LOCAL_STORAGE_DIR) {
    return process.env.LOCAL_STORAGE_DIR;
  }
  let current = process.cwd();
  for (let depth = 0; depth < 6; depth += 1) {
    if (existsSync(path.join(current, "convex"))) {
      return path.join(current, ".local-storage");
    }
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return path.join(process.cwd(), ".local-storage");
}

/**
 * Matches keys generated by generateS3Key: users/{userId}/{timestamp}-{uuid}.{ext}
 * Strict validation prevents path traversal on the local filesystem.
 */
const LOCAL_STORAGE_KEY_PATTERN =
  /^users\/[A-Za-z0-9_.-]{1,128}\/\d{1,20}-[0-9a-fA-F-]{1,64}(\.[A-Za-z0-9]{1,20})?$/;

export function isLocalStorageKey(s3Key: string): boolean {
  return LOCAL_STORAGE_KEY_PATTERN.test(s3Key);
}

/**
 * Resolve an s3Key to a safe absolute path under the local storage dir.
 */
export function localStorageFilePath(s3Key: string): string {
  if (!isLocalStorageKey(s3Key)) {
    throw new Error(`Invalid storage key: ${s3Key}`);
  }
  return path.join(
    /* turbopackIgnore: true */ getLocalStorageDir(),
    s3Key,
  );
}

/**
 * Generate unique S3 key with user prefix
 * Format: users/{userId}/{timestamp}-{uuid}.{ext}
 * Only uses file extension from fileName, UUID ensures uniqueness
 */
export function generateS3Key(userId: string, fileName: string): string {
  const timestamp = Date.now();
  const uuid = uuidv4();

  // Extract file extension, default to empty string if none
  const lastDotIndex = fileName.lastIndexOf(".");
  const extension = lastDotIndex !== -1 ? fileName.substring(lastDotIndex) : "";

  return `${S3_USER_FILES_PREFIX}/${userId}/${timestamp}-${uuid}${extension}`;
}

/**
 * Generate upload URL for a file. Uses S3 presigned URLs when S3 is
 * configured, otherwise returns a local-storage endpoint URL.
 */
export async function generateS3UploadUrl(
  fileName: string,
  contentType: string,
  userId: string,
  contentLength?: number,
): Promise<{ uploadUrl: string; s3Key: string }> {
  const s3Key = generateS3Key(userId, fileName);

  if (!isS3Configured()) {
    const uploadUrl = `${getLocalStorageBaseUrl()}/api/local-storage/upload?key=${encodeURIComponent(s3Key)}`;
    return { uploadUrl, s3Key };
  }

  try {
    const s3Client = getS3Client();
    const bucketName = getRequiredEnvVar("AWS_S3_BUCKET_NAME");

    const command = new PutObjectCommand({
      Bucket: bucketName,
      Key: s3Key,
      ContentType: contentType,
      ContentLength: contentLength,
    });

    const uploadUrl = await getSignedUrl(s3Client, command, {
      expiresIn: getS3UrlLifetimeSeconds(),
    });

    return { uploadUrl, s3Key };
  } catch (error) {
    console.error("Failed to generate S3 upload URL:", error);
    throw new Error(
      "Failed to generate upload URL: " +
        (error instanceof Error ? error.message : "Unknown error"),
    );
  }
}

/**
 * Generate download URL for a file. Uses S3 presigned URLs when S3 is
 * configured, otherwise returns a local-storage endpoint URL.
 */
export async function generateS3DownloadUrl(s3Key: string): Promise<string> {
  if (!isS3Configured()) {
    return `${getLocalStorageBaseUrl()}/api/local-storage/file?key=${encodeURIComponent(s3Key)}`;
  }

  try {
    const s3Client = getS3Client();
    const bucketName = getRequiredEnvVar("AWS_S3_BUCKET_NAME");

    const command = new GetObjectCommand({
      Bucket: bucketName,
      Key: s3Key,
    });

    const downloadUrl = await getSignedUrl(s3Client, command, {
      expiresIn: getS3UrlLifetimeSeconds(),
    });

    return downloadUrl;
  } catch (error) {
    console.error("Failed to generate S3 download URL:", error);
    throw new Error(
      "Failed to generate download URL: " +
        (error instanceof Error ? error.message : "Unknown error"),
    );
  }
}

/**
 * Delete object from storage (S3 or local fallback).
 */
export async function deleteS3Object(s3Key: string): Promise<void> {
  if (!isS3Configured()) {
    if (!isLocalStorageKey(s3Key)) {
      return;
    }
    await fs.rm(localStorageFilePath(s3Key), { force: true });
    return;
  }

  try {
    const s3Client = getS3Client();
    const bucketName = getRequiredEnvVar("AWS_S3_BUCKET_NAME");

    const command = new DeleteObjectCommand({
      Bucket: bucketName,
      Key: s3Key,
    });

    await s3Client.send(command);
  } catch (error) {
    console.error("Failed to delete S3 object:", error);
    throw new Error(
      "Failed to delete S3 object: " +
        (error instanceof Error ? error.message : "Unknown error"),
    );
  }
}

/**
 * Get object size in bytes (S3 or local fallback).
 */
export async function getS3ObjectSizeBytes(s3Key: string): Promise<number> {
  if (!isS3Configured()) {
    const stat = await fs.stat(
      /* turbopackIgnore: true */ localStorageFilePath(s3Key),
    );
    return stat.size;
  }

  try {
    const s3Client = getS3Client();
    const bucketName = getRequiredEnvVar("AWS_S3_BUCKET_NAME");

    const command = new HeadObjectCommand({
      Bucket: bucketName,
      Key: s3Key,
    });

    const result = await s3Client.send(command);
    if (typeof result.ContentLength !== "number") {
      throw new Error("S3 object ContentLength is missing");
    }
    return result.ContentLength;
  } catch (error) {
    console.error("Failed to fetch S3 object metadata:", error);
    throw new Error(
      "Failed to fetch S3 object metadata: " +
        (error instanceof Error ? error.message : "Unknown error"),
    );
  }
}
