import { customProvider } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import { createOpenAI } from "@ai-sdk/openai";
import { randomBytes } from "node:crypto";
import type { ChatMode, SelectedModel } from "@/types/chat";
import { openrouterAttributionHeaders } from "@/lib/ai/openrouter-attribution";
import { isOpenCodeZenEnabled } from "@/lib/auth/personal-mode";
import { createKiroProvider } from "./providers/kiro";
import {
  getKiroModelName,
  isKiroModelKey,
  KIRO_DEFAULT_CUTOFF,
  KIRO_MODEL_KEYS,
  KIRO_MODELS,
} from "./providers/kiro-models";
import {
  createOllamaProvider,
  getOllamaModelName,
  isOllamaModelKey,
} from "./providers/ollama";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

const isXaiModelSlug = (value: unknown): boolean =>
  typeof value === "string" && value.toLowerCase().startsWith("x-ai/");

const requestCanRouteToXai = (body: unknown): boolean => {
  if (!isRecord(body)) return false;
  if (isXaiModelSlug(body.model)) return true;
  return Array.isArray(body.models) && body.models.some(isXaiModelSlug);
};

const hasOwnEncryptedContent = (value: unknown): boolean =>
  isRecord(value) && Object.hasOwn(value, "encrypted_content");

// OpenRouter 2.10 uses this shape for provider-private reasoning blobs.
const isEncryptedReasoningDetail = (value: unknown): boolean =>
  isRecord(value) &&
  (hasOwnEncryptedContent(value) || value.type === "reasoning.encrypted");

const stripEncryptedContent = (
  value: unknown,
  inReasoningDetails = false,
): { value: unknown; changed: boolean } => {
  if (Array.isArray(value)) {
    let changed = false;
    const cleaned: unknown[] = [];

    for (const item of value) {
      if (inReasoningDetails && isEncryptedReasoningDetail(item)) {
        changed = true;
        continue;
      }
      const result = stripEncryptedContent(item, inReasoningDetails);
      changed ||= result.changed;
      cleaned.push(result.value);
    }

    return changed ? { value: cleaned, changed } : { value, changed: false };
  }

  if (!isRecord(value)) {
    return { value, changed: false };
  }

  let changed = false;
  const cleaned: Record<string, unknown> = {};

  for (const [key, entryValue] of Object.entries(value)) {
    if (inReasoningDetails && key === "encrypted_content") {
      changed = true;
      continue;
    }

    const nextInReasoningDetails =
      inReasoningDetails || key === "reasoning_details";
    const result = stripEncryptedContent(entryValue, nextInReasoningDetails);
    changed ||= result.changed;

    if (
      key === "reasoning_details" &&
      Array.isArray(result.value) &&
      result.value.length === 0
    ) {
      changed = true;
      continue;
    }

    cleaned[key] = result.value;
  }

  return changed ? { value: cleaned, changed } : { value, changed: false };
};

export const sanitizeOpenRouterRequestForXai = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (
    !isRecord(body) ||
    !requestCanRouteToXai(body) ||
    !Array.isArray(body.messages)
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    const result = stripEncryptedContent(message);
    changed ||= result.changed;
    return result.value;
  });

  if (!changed) return { body, changed: false };
  return { body: { ...body, messages }, changed: true };
};

const patchKimiReasoningToolCalls = (
  body: unknown,
): { body: unknown; changed: boolean } => {
  if (!isRecord(body)) return { body, changed: false };
  if (
    !Array.isArray(body.messages) ||
    !isRecord(body.reasoning) ||
    body.reasoning.enabled !== true
  ) {
    return { body, changed: false };
  }

  let changed = false;
  const messages = body.messages.map((message) => {
    if (
      isRecord(message) &&
      message.role === "assistant" &&
      Array.isArray(message.tool_calls) &&
      message.tool_calls.length > 0 &&
      !message.reasoning
    ) {
      changed = true;
      return { ...message, reasoning: "." };
    }
    return message;
  });

  return changed
    ? { body: { ...body, messages }, changed: true }
    : { body, changed: false };
};

const OPENROUTER_METADATA_HEADER = "X-OpenRouter-Experimental-Metadata";

const withOpenRouterMetadataHeader = (
  headers: HeadersInit | undefined,
): Headers => {
  const nextHeaders = new Headers(headers);
  if (!nextHeaders.has(OPENROUTER_METADATA_HEADER)) {
    nextHeaders.set(OPENROUTER_METADATA_HEADER, "enabled");
  }
  return nextHeaders;
};

// Custom fetch for OpenRouter provider-specific request-body repairs.
//
// - Kimi requires a `reasoning` field on assistant tool-call messages when
//   reasoning mode is enabled, but the AI SDK does not always include one.
// - xAI rejects encrypted reasoning blobs generated by a different provider
//   when OpenRouter falls back to Grok. The visible assistant text remains in
//   the prompt, so these provider-private blobs are safe to omit for xAI routes.
// - The metadata header opts into OpenRouter routing metadata for attribution.
const openrouterPatchFetch: typeof fetch = async (url, init) => {
  let nextInit: RequestInit = {
    ...init,
    headers: withOpenRouterMetadataHeader(init?.headers),
  };

  if (nextInit.body && typeof nextInit.body === "string") {
    try {
      const parsedBody = JSON.parse(nextInit.body) as unknown;
      const kimiPatched = patchKimiReasoningToolCalls(parsedBody);
      const xaiPatched = sanitizeOpenRouterRequestForXai(kimiPatched.body);
      if (kimiPatched.changed || xaiPatched.changed) {
        nextInit = { ...nextInit, body: JSON.stringify(xaiPatched.body) };
      }
    } catch {
      // If parsing fails, send the request as-is
    }
  }
  return globalThis.fetch(url, nextInit);
};

const openrouter = createOpenRouter({
  fetch: openrouterPatchFetch,
  headers: openrouterAttributionHeaders,
});

export const KIMI_K3_SLUG = "moonshotai/kimi-k3";
export const GLM_5_2_SLUG = "z-ai/glm-5.2";
export const GROK_4_5_SLUG = "x-ai/grok-4.5";
export const GROK_4_6_SLUG = "x-ai/grok-4.6";
// MiMo-V2.5 is an open-weight multimodal model that avoids Google safety filters
// while retaining low-latency OCR and screen understanding for security work.
export const AUXILIARY_VISION_SLUG = "xiaomi/mimo-v2.5";
export const DEEPSEEK_V4_PRO_SLUG = "deepseek/deepseek-v4-pro";
export const DEEPSEEK_V4_PRO_0813_SLUG = "deepseek/deepseek-v4-pro-0813";
export const DEEPSEEK_V4_FLASH_SLUG = "deepseek/deepseek-v4-flash-0731";
export const DEEPSEEK_V4_FLASH_PREVIOUS_SLUG = "deepseek/deepseek-v4-flash";

// Known Zen free models (fallback when API unavailable).
// Synced 2026-09-05 against GET /api/zen/models: hy3-free,
// laguna-s-2.1-free and x-preview-f-free were removed by the provider
// (requests 401) and ling-3.0-flash-fin-free / muse-spark-1.3-contributor-free
// were added. Re-check the live list if a "-free" model starts 401ing.
export const KNOWN_ZEN_FREE_MODELS = [
  "deepseek-v4-flash-free",
  "ling-3.0-flash-fin-free",
  "mimo-v2.5-free",
  "muse-spark-1.2-contributor-free",
  "muse-spark-1.3-contributor-free",
  "nemotron-3-ultra-free",
  "nemotron-3.5-lightning-free",
  "big-pickle",
] as const;

export function isKnownZenFreeModelId(value: string): boolean {
  return (
    value.endsWith("-free") ||
    (KNOWN_ZEN_FREE_MODELS as readonly string[]).includes(value)
  );
}

export function isZenModelId(value: string): boolean {
  return isKnownZenFreeModelId(value);
}

const TITLE_GENERATOR_DEEPSEEK_SLUG = "deepseek/deepseek-v4-flash";
const DEFAULT_ZEN_MODEL = "deepseek-v4-flash-free";

const resolveZenModelId = (openRouterSlug: string): string => {
  // Direct Zen free model IDs pass through unchanged (for explicit user selection)
  if (isKnownZenFreeModelId(openRouterSlug)) {
    return openRouterSlug;
  }
  const configured = process.env.OPENCODE_ZEN_MODEL?.trim();
  const standard =
    process.env.OPENCODE_ZEN_MODEL_STANDARD?.trim() ||
    configured ||
    DEFAULT_ZEN_MODEL;
  const pro =
    process.env.OPENCODE_ZEN_MODEL_PRO?.trim() || configured || DEFAULT_ZEN_MODEL;
  const max =
    process.env.OPENCODE_ZEN_MODEL_MAX?.trim() || configured || DEFAULT_ZEN_MODEL;
  const vision =
    process.env.OPENCODE_ZEN_MODEL_VISION?.trim() || "mimo-v2.5-free";

  if (openRouterSlug === AUXILIARY_VISION_SLUG) return vision;
  if (
    openRouterSlug === DEEPSEEK_V4_PRO_SLUG ||
    openRouterSlug === DEEPSEEK_V4_PRO_0813_SLUG
  ) {
    return pro;
  }
  if (
    openRouterSlug === KIMI_K3_SLUG ||
    openRouterSlug === GROK_4_6_SLUG ||
    openRouterSlug === GROK_4_5_SLUG ||
    openRouterSlug === GLM_5_2_SLUG
  ) {
    return max;
  }
  return standard;
};

type LanguageModelFactory = (slug: string) => unknown;

// The OpenCode Zen anonymous free tier rejects requests unless they mimic the
// official CLI: `Authorization: Bearer public` plus x-opencode-* session
// headers. Without these, the gateway answers 429 FreeUsageLimitError even
// though the anonymous tier is enabled.
const zenPatchFetch: typeof fetch = async (url, init) => {
  const headers = new Headers(init?.headers);
  const auth = headers.get("authorization");
  if (!auth || auth === "Bearer " || auth === "Bearer") {
    headers.set("Authorization", "Bearer public");
  }
  if (!headers.has("x-opencode-client")) headers.set("x-opencode-client", "cli");
  if (!headers.has("x-opencode-project")) headers.set("x-opencode-project", "global");
  if (!headers.has("x-opencode-request")) {
    headers.set("x-opencode-request", `msg_${randomBytes(16).toString("hex")}`);
  }
  if (!headers.has("x-opencode-session")) {
    headers.set("x-opencode-session", `ses_${randomBytes(16).toString("hex")}`);
  }
  if (!headers.has("user-agent")) {
    headers.set("User-Agent", "opencode/1.15.0 ai-sdk/provider-utils/4.0.23");
  }
  return globalThis.fetch(url, { ...init, headers });
};

const createLanguageModelFactory = (): LanguageModelFactory => {
  if (!isOpenCodeZenEnabled()) {
    return (slug: string) => openrouter(slug);
  }

  const zen = createOpenAI({
    name: "opencode-zen",
    apiKey: process.env.OPENCODE_ZEN_API_KEY,
    baseURL:
      process.env.OPENCODE_ZEN_BASE_URL?.trim() || "https://opencode.ai/zen/v1",
    fetch: zenPatchFetch,
  });

  return (slug: string) =>
    zen.chat(resolveZenModelId(slug) as Parameters<typeof zen.chat>[0]);
};

export const getOpenRouterProviderRoutingForModel = (
  modelSlug: string,
): { ignore: string[] } | undefined =>
  modelSlug === DEEPSEEK_V4_FLASH_PREVIOUS_SLUG
    ? { ignore: ["novita"] }
    : undefined;

const buildProviderMap = (
  or: LanguageModelFactory,
  freeAskDeepSeekSlug = DEEPSEEK_V4_FLASH_PREVIOUS_SLUG,
  freeAgentDeepSeekSlug = DEEPSEEK_V4_FLASH_SLUG,
) =>
  ({
    "ask-model": or(GROK_4_6_SLUG),
    "ask-model-free": or(freeAskDeepSeekSlug),
    "agent-model": or(GROK_4_6_SLUG),
    "agent-model-free": or(freeAgentDeepSeekSlug),
    "model-grok-4.6": or(GROK_4_6_SLUG),
    // Separate internal keys use the same Grok 4.5 provider model while
    // provider reasoning options distinguish Standard from Pro vision.
    "model-grok-4.5": or(GROK_4_5_SLUG),
    "model-grok-4.5-pro": or(GROK_4_5_SLUG),
    "model-grok-4.6-pro": or(GROK_4_6_SLUG),
    "model-deepseek-v4-flash-0731": or(DEEPSEEK_V4_FLASH_SLUG),
    "model-deepseek-v4-pro": or(DEEPSEEK_V4_PRO_SLUG),
    "model-deepseek-v4-pro-0813": or(DEEPSEEK_V4_PRO_0813_SLUG),
    // Keep the persisted Max compatibility key while routing new requests to
    // Kimi K3. Renaming the key would invalidate existing stored selections.
    "model-opus-4.6": or(KIMI_K3_SLUG),
    "model-glm-5.2": or(GLM_5_2_SLUG),
    "model-kimi-k3": or(KIMI_K3_SLUG),
    "fallback-agent-model": or(GROK_4_6_SLUG),
    "fallback-ask-model": or(GROK_4_6_SLUG),
    // Titles are a short structured-output task and should never use reasoning.
    "title-generator-model": or(TITLE_GENERATOR_DEEPSEEK_SLUG),
    // Separate text-only, tool-less call used to review one approval-gated
    // action. The reviewer receives serialized evidence rather than images.
    "agent-auto-review-model": or(DEEPSEEK_V4_FLASH_SLUG),
    // Image understanding for text-only routes. The resulting description is
    // injected as untrusted text; this model never becomes the active agent.
    "auxiliary-vision-model": or(AUXILIARY_VISION_SLUG),
  }) as Record<string, any>;

// Add direct Zen free model entries for explicit user selection (e.g., via ModelSelector)
const buildZenFreeProviders = (or: LanguageModelFactory) =>
  Object.fromEntries(
    KNOWN_ZEN_FREE_MODELS.map((id) => [id, or(id)]),
  ) as Record<string, any>;

const kiroFactory = createKiroProvider();
const kiroProviders = Object.fromEntries(
  Object.keys(KIRO_MODELS).map((k) => [k, kiroFactory(k)]),
) as Record<string, any>;

const ollamaFactory = createOllamaProvider();

const baseProviders = {
  ...buildProviderMap(createLanguageModelFactory()),
  ...buildZenFreeProviders(createLanguageModelFactory()),
  ...kiroProviders,
} as Record<string, any>;

// Also handle any future free models dynamically (e.g., new -free suffix)
const zenFreeModelFallback = (modelName: string) => {
  if (isKnownZenFreeModelId(modelName) && !(modelName in baseProviders)) {
    const or = createLanguageModelFactory();
    return or(modelName);
  }
  return null;
};

export type ModelName = keyof typeof baseProviders;

export const modelCutoffDates: Partial<Record<ModelName, string>> &
  Record<string, string | undefined> = {
  "ask-model": "August 2026",
  "agent-model": "August 2026",
  "model-grok-4.6": "August 2026",
  "model-grok-4.6-pro": "August 2026",
  "model-deepseek-v4-flash-0731": "July 2026",
  "model-deepseek-v4-pro": "May 2025",
  "model-deepseek-v4-pro-0813": "August 2026",
  "model-opus-4.6": "July 2026",
  "model-glm-5.2": "June 2026",
  "fallback-agent-model": "August 2026",
  "fallback-ask-model": "August 2026",
  "title-generator-model": "May 2025",
  "agent-auto-review-model": "July 2026",
  "auxiliary-vision-model": "January 2025",
  // Zen free models
  "deepseek-v4-flash-free": "July 2026",
  "mimo-v2.5-free": "January 2025",
  "muse-spark-1.2-contributor-free": "August 2026",
  "nemotron-3-ultra-free": "August 2026",
  "nemotron-3.5-lightning-free": "August 2026",
  "big-pickle": "August 2026",
  // Kiro models, derived from the catalog so that adding a model there (or
  // picking up a new one from the gateway) stays in sync automatically.
  ...Object.fromEntries(
    KIRO_MODEL_KEYS.map((key) => [key, KIRO_DEFAULT_CUTOFF]),
  ),
};

export const modelDisplayNames: Record<ModelName, string> &
  Record<string, string> = {
  "ask-model": "Auto, an intelligent model router built by HackerAI",
  "ask-model-free": "Auto, an intelligent model router built by HackerAI",
  "agent-model": "Auto, an intelligent model router built by HackerAI",
  "agent-model-free": "Auto, an intelligent model router built by HackerAI",
  "model-grok-4.6": "xAI Grok 4.6",
  "model-grok-4.5": "xAI Grok 4.5",
  "model-grok-4.5-pro": "xAI Grok 4.5",
  "model-grok-4.6-pro": "xAI Grok 4.6",
  "model-deepseek-v4-flash-0731": "DeepSeek V4 Flash 0731",
  "model-deepseek-v4-pro": "DeepSeek V4 Pro",
  "model-deepseek-v4-pro-0813": "DeepSeek V4 Pro 0813",
  "model-opus-4.6": "Moonshot Kimi K3",
  "model-glm-5.2": "Z.ai GLM 5.2",
  "model-kimi-k3": "Moonshot Kimi K3",
  "fallback-agent-model": "Auto, an intelligent model router built by HackerAI",
  "fallback-ask-model": "Auto, an intelligent model router built by HackerAI",
  "title-generator-model": "DeepSeek V4 Flash",
  "agent-auto-review-model": "DeepSeek V4 Flash 0731",
  "auxiliary-vision-model": "Auxiliary vision model",
  // Zen free models (display names for ModelSelector)
  "deepseek-v4-flash-free": "DeepSeek V4 Flash (Free)",
  "mimo-v2.5-free": "MiMo V2.5 (Free)",
  "muse-spark-1.2-contributor-free": "Muse Spark 1.2 (Free)",
  "nemotron-3-ultra-free": "Nemotron 3 Ultra (Free)",
  "nemotron-3.5-lightning-free": "Nemotron 3.5 Lightning (Free)",
  "big-pickle": "Big Pickle (Free)",
  // Kiro models, derived from the catalog (see `modelCutoffDates` above).
  ...Object.fromEntries(
    KIRO_MODEL_KEYS.map((key) => [key, getKiroModelName(key)]),
  ),
};

export const getModelDisplayName = (modelName: ModelName): string => {
  if (modelDisplayNames[modelName]) return modelDisplayNames[modelName];
  // Gateway-only Kiro models absent from the static catalog get a derived label.
  if (isKiroModelKey(modelName)) return getKiroModelName(modelName);
  // Locally installed Ollama models are discovered at runtime.
  if (isOllamaModelKey(modelName)) return getOllamaModelName(modelName);
  if (
    isKnownZenFreeModelId(modelName) &&
    (KNOWN_ZEN_FREE_MODELS as readonly string[]).includes(modelName)
  ) {
    return (
      modelName
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ") + " (Free)"
    );
  }
  return modelDisplayNames[modelName] ?? modelName;
};

export const getModelCutoffDate = (
  modelName: ModelName,
): string | undefined => {
  if (modelCutoffDates[modelName]) return modelCutoffDates[modelName];
  if ((KNOWN_ZEN_FREE_MODELS as readonly string[]).includes(modelName))
    return "August 2026";
  if (isKiroModelKey(modelName)) return KIRO_DEFAULT_CUTOFF;
  if (isOllamaModelKey(modelName)) return undefined;
  return modelCutoffDates[modelName];
};

export function isAnthropicModel(modelName: string): boolean {
  const normalized = modelName.toLowerCase();
  // Every model served by the Kiro Gateway is Bedrock Claude underneath:
  // `GET /v1/models` reports `owned_by: "anthropic"` and description
  // "Claude model via Kiro API" for all 19, and tool-call ids come back as
  // `toolu_bdrk_*`. Their public names do not all contain "claude"
  // (`kiro-gpt-5.6-sol`, `kiro-glm-5`, `kiro-minimax-m2.5`, `kiro-auto`), so a
  // substring match alone routed them down the generic path — skipping
  // Anthropic prompt repair (which drops orphaned trailing tool_use blocks
  // that Anthropic rejects) and provider cache breakpoints.
  if (isKiroModelKey(normalized)) return true;
  return normalized.startsWith("anthropic/") || normalized.includes("claude");
}

/** Returns whether a provider key uses a DeepSeek V4 route. */
export function isDeepSeekModel(modelName: string): boolean {
  return (
    modelName === "ask-model-free" ||
    modelName === "agent-model-free" ||
    modelName === "agent-auto-review-model" ||
    modelName === "model-deepseek-v4-flash-0731" ||
    modelName === "model-deepseek-v4-pro" ||
    modelName === "model-deepseek-v4-pro-0813"
  );
}

export function isKimiModel(modelName: string): boolean {
  const normalized = modelName.toLowerCase();
  return (
    normalized === "model-kimi-k3" ||
    normalized === "model-opus-4.6" ||
    normalized.includes("moonshotai/kimi")
  );
}

function isGrokModel(modelName: string): boolean {
  const normalized = modelName.toLowerCase();
  return (
    normalized === "agent-model" ||
    normalized === "ask-model" ||
    normalized === "fallback-agent-model" ||
    normalized === "fallback-ask-model" ||
    normalized === "model-grok-4.6" ||
    normalized === "model-grok-4.5" ||
    normalized === "model-grok-4.5-pro" ||
    normalized === "model-grok-4.6-pro" ||
    normalized.includes("x-ai/") ||
    normalized === "grok-4.5" ||
    normalized === "grok-4.6"
  );
}

export function supportsMultimodalToolResults(modelName?: string): boolean {
  if (!modelName) return false;

  const normalized = modelName.toLowerCase();

  return (
    isKimiModel(normalized) ||
    isGrokModel(normalized) ||
    isAnthropicModel(normalized) ||
    normalized.includes("anthropic/") ||
    normalized.includes("claude") ||
    normalized.includes("openai/") ||
    normalized.includes("gpt-") ||
    normalized.includes("o1") ||
    normalized.includes("o3") ||
    normalized.includes("o4")
  );
}

/**
 * Map a HackerAI tier id to the underlying provider key for a given mode.
 * Returns `null` for `"auto"` (the caller routes to the auto-router model
 * key instead). Standard maps to DeepSeek V4 Flash 0731, Pro to DeepSeek V4
 * Pro 0813, and Max to Grok 4.6 in both modes; media-aware promotion happens
 * in `selectModel`.
 */
export function resolveTierToProviderKey(
  tier: SelectedModel,
  _mode: ChatMode,
): ModelName | null {
  if (tier === "auto") return null;
  // Direct Zen free model selection (e.g., from ModelSelector) passes through
  if (isKnownZenFreeModelId(tier)) {
    return tier as ModelName;
  }
  // Direct Kiro gateway model selection also bypasses tier mapping.
  if (typeof tier === "string" && isKiroModelKey(tier)) {
    return tier as ModelName;
  }
  // Local Ollama models are direct selections too.
  if (typeof tier === "string" && isOllamaModelKey(tier)) {
    return tier as ModelName;
  }
  switch (tier) {
    case "hackerai-standard":
      return "model-deepseek-v4-flash-0731";
    case "hackerai-pro":
      return "model-deepseek-v4-pro-0813";
    case "hackerai-max":
      return "model-grok-4.6";
  }
  // Fallback for any future zen -free ids not in static list
  if (typeof tier === "string" && tier.endsWith("-free")) {
    return tier as ModelName;
  }
  return null;
}

// Wrap baseProviders to handle dynamic Zen free models not in the static map
const baseMyProvider = customProvider({
  languageModels: baseProviders,
});

export const myProvider = {
  ...baseMyProvider,
  languageModel: (modelId: string) => {
    if (modelId in baseProviders) {
      return (baseMyProvider as any).languageModel(modelId);
    }
    if (isKnownZenFreeModelId(modelId)) {
      const or = createLanguageModelFactory();
      return or(modelId);
    }
    // Kiro models the gateway exposes but the static catalog doesn't list yet.
    if (isKiroModelKey(modelId)) {
      return kiroFactory(modelId);
    }
    // Local Ollama models, resolved from the daemon's catalog at runtime.
    if (isOllamaModelKey(modelId)) {
      return ollamaFactory(modelId);
    }
    // Fallback to base provider (will throw if not found, preserving original behavior)
    return (baseMyProvider as any).languageModel(modelId);
  },
} as typeof baseMyProvider;

export const createTrackedProvider = () => myProvider;
